import React, { Fragment } from "react";
import { Card, CardBody } from "reactstrap";

const Policy = () => {
  return (
    <Fragment>
      <Card className="terms_policy_card_height ">
        <div className="h1 mt-3 text-center">
          <b>PRIVACY POLICY – LEGISTIFY - NOTICE</b>
        </div>
        <CardBody className="p-3 pt-2  ">
          <p>
            We at <b> Legistify Services Private Limited (‘Company’)</b> value
            our Users and respect their privacy. This Privacy Policy (the{" "}
            <b>‘Policy’</b>) is applicable to our Website, domain name, page,
            URL and/or any other such features and/or media using the domain
            name <b>corporate.legistify.com</b> or anyother name as may be
            informed by the Company to the Users. We may collect, store, use and
            process certain data and information provided by You by accessing
            and using the Website and/or the said or related page or URL
            (together, the <b>‘Website’</b>). In pursuance of the foregoing,
            this Policy delineates inter alia the manner of collection, storage,
            usage and processing of Your information by us including the type of
            information collected, the manner of collection, the purpose of
            collection and intended use, disclosure of information, etc. By
            accessing and using the Website, You consent to the provisions
            stipulated in this Policy with regard to Your information as
            aforesaid. You are advised to carefully read this Policy prior to
            using and accessing the Website and in the event, You disagree with
            its provisions, discontinue such use and access. The terms{" "}
            <b>‘We’, ‘Us’, ‘Our’</b> refer to the Company and{" "}
            <b>‘You’, ‘Your’</b> refer to the Users of the Website.
          </p>
          <p>
            <b>1. Type of Information and Manner of Collection</b>
          </p>
          <p>
            Your usage of the Website and availing the services, and features on
            offer shall entail the collection by us of Your personally
            identifiable information, sensitive personal data and information
            and certain other information for the purpose of providing the
            services on the Website. The information collected by us can be
            categorized into the types delineated below.
          </p>
          <p>
            <b>Personal Information</b>
          </p>
          <p>
            Your personal information collected by us shall include Your name
            and contact details including telephone number, postal address,
            email ID. It is pertinent to note that the mere browsing of the
            Website by You shall not require You to provide or submit to us the
            foregoing information and such information shall be collected and
            stored by us only if You voluntarily submit such information on the
            Website for the purposes of subscribing and availing the services
            available therein. You may in Your discretion choose not to provide
            such information by not availing of the services, and features on
            the Website.
          </p>
          <p>
            <b>Other Information</b>
          </p>
          <p>
            Our Website uses technologies such as cookies, web beacons, log data
            and third-party analytics for data collection and analysis. In
            addition to the information stipulated above we may trace, collect
            and store information pertaining to Your activity on the Website
            including log files, searches, pages, interactions and messages,
            date and time of usage and device information including Your IP
            (Internet Protocol) address, geographical location, browser,
            operating system etc. using cookies and other tracking tools and
            technologies so as to analyse Your usage patterns and behaviours and
            develop an understanding of Your needs and preferences to customize
            our Website, features, and services accordingly. The aforesaid
            information is collected when You use and interact with our Website.
          </p>
          <p>
            <i>
              Cookies: When You browse on a Website using a browser, certain
              data generated by the Website is stored on the browser to remember
              information about You. This is done so as to recognize Your device
              and set Your preferences as per Your usage of the Website. We use
              session and persistent cookies wherein session cookies enable You
              to stay logged in on the Website and persistent cookies recognize
              You every time You return.
            </i>
          </p>
          <p>
            The type of information collected and the manner of collection shall
            correspond to Your usage of the Website and the service or feature
            availed by You. The various stages at which Your information shall
            be collected and stored by us include:
          </p>
          <p>i. When You subscribe and create an account on the Website.</p>
          <p>
            ii. When You create and manage Your profile including modifications
            and alterations thereof.
          </p>
          <p>iii. When You sign up for receiving communications.</p>
          <p>
            iv. When You participate in any surveys, sweepstakes, contests, and
            promotions.
          </p>
          <p>v. When You communicate with and contact our customer services.</p>
          <p>
            <b>2. Purpose of Collection and Usage</b>
          </p>
          <p>
            We assure You that the information collected and stored by us shall
            not be used and processed for any unlawful, illegal or illicit
            purposes and shall be used only for the purpose of providing the
            services on Website. The information collected by us is used for the
            following purposes:
          </p>
          <p>
            i. Creation and management of Your account and profile and
            authenticating access.
          </p>
          <p>
            ii. Communications to provide You with information regarding
            services including promotional offers, special sales, events
            (whether sponsored by us or others) via email, telephone, text and
            other means.
          </p>
          <p>
            iii. Analysis and evaluation of Your behavior and preferences by
            using information using cookies and web beacons, developing and
            aggregating statistics, demographic reports, usage patterns and
            improving and customizing the services, features, and overall
            experience accordingly.
          </p>
          <p>iv. Provided targeted and interest-based advertising.</p>
          <p>v. Notify You of new services and features on the Website.</p>
          <p>
            vi. Providing customer support and promptly respond to and resolve
            Your queries, complaints, and grievances, if any.
          </p>
          <p>
            <b>3. Disclosures</b>
          </p>
          <p>
            i. The information collected by us shall not in any manner be
            disclosed to any unaffiliated third-party. We may, however, disclose
            Your information to our domestic or international affiliates,
            subsidiaries, joint venture partners, licensees, and
            representatives, solely for the purposes stipulated in this Privacy
            Policy.
          </p>
          <p>
            ii. We may work with and outsource certain services to third-party
            service providers so as to enable us to provide our products and
            services more efficiently. The outsourced services may include
            without limitation a) Website development and maintenance b) hosting
            c) backup and storage d) payment processing e) analysis f) customer
            database management g) direct marketing and data collection h)
            providing customer services by phone i) and such other services in
            order to maximize our business. In pursuance of the aforementioned
            outsourcing, we may disclose Your information to such third-party
            service providers. We shall ensure the protection and
            confidentiality of the information provided to such service
            providers by apprising them of their confidentiality obligations
            pertaining to the information.
          </p>
          <p>
            iii. We may disclose the aggregated statistics, demographic reports
            developed by us by analyzing Your usage patterns and behavior to
            third parties. Such statistics and reports contain anonymous
            information such as age gender, preferences, pages frequently
            visited that does not constitute personally identifiable
            information. The information is used in a manner such that no single
            person can be identified using such compilations.
          </p>
          <p>
            iv. In the event of a transfer of our business, undertaking or
            assets, whether in whole or in part as a result of a merger,
            acquisition, restructuring, reorganization or otherwise Your
            information may be disclosed to the transferee to the extent of such
            transfer, and we shall make reasonable efforts to protect Your
            information in accordance with our Privacy Policy. You may contact
            the transferee entity to inquire about the processing of Your
            information as it may be subject to the new entity’s Privacy Policy.
          </p>
          <p>
            v. We may disclose Your information for the purpose of responding to
            subpoenas, enforcing our Terms and Conditions, protection of our and
            our users’ rights, reputation and property, take action against any
            illegal activity.
          </p>
          <p>
            vi. The information shall be shared without prior consent in the
            event it is mandated by a government or law enforcement agency or
            authority under any law, or under a court order for the purposes of
            identity verification, or for the prevention, detection,
            investigation including cyber incidents, fraud, threats,
            prosecution, and punishment for offenses.
          </p>
          <p>
            <b>4. Security and Disclaimer</b>
          </p>
          <p>
            We employ reasonable security practices, policies, procedures and
            standards to ensure the security, integrity, and confidentiality of
            the information provided by You which includes limiting the access
            to our database servers and employing electronic security systems
            and password protections to guard against unauthorized access. Our
            customer service team works over a secure and private network.{" "}
          </p>
          <p>
            Although we use our best endeavors to protect and secure Your
            information, transmission of information over the internet and
            wireless connections is never completely secure and we do not
            guarantee the protection of Your information over such transmission
            or in the event of any external breach beyond our control. In the
            event of any such breach, we shall endeavour to promptly notify You
            of the same.
          </p>
          <p>
            We do not collect Your personal information unless it is voluntarily
            provided by You and You are solely responsible for the accuracy and
            authenticity of the information provided or submitted by You and we
            do not bear any responsibility for the same.
          </p>
          <p>
            <b>5. Password</b>
          </p>
          <p>
            The protection and confidentiality of Your username and password is
            solely Your responsibility and we urge You to not disclose it to
            anyone including anyone claiming to represent the Website or its
            affiliates. We shall not bear any responsibility or liability for
            any such unauthorized disclosure and its consequences.
          </p>
          <p>
            <b>6. Amendments</b>
          </p>
          <p>
            The Company reserves the right to make amendments to this Privacy
            Policy from time to time without any notification and the updated
            versions shall be posted on the Website. You are requested to
            periodically review the Policy so as to apprise Yourself of the
            requisite changes as all such changes shall be effective immediately
            on posting the updated Policy on the Website.
          </p>
          <p>
            <b>7. Data Retention</b>
          </p>
          <p>
            Your information is retained by us to the extent it may be required
            to comply with any legal obligations, fraud prevention, enforcing
            agreements, protection of the Website and the users and for
            improving our services and business.{" "}
          </p>
          <p>8. Third-party Links and Websites</p>
          <p>
            The Website may contain links to third-party Websites and Websites
            and the same shall not constitute, in any manner whatsoever the
            Company’s endorsement, sponsorship, or recommendation of such
            third-party Websites or their products, services, content, and
            offerings. The Company is not responsible for examining or
            evaluating any third-party Websites and does not make any
            representation or warranty for their products, services, content,
            and offerings or their terms of use and privacy practices. In the
            event a User accesses such Websites he/she shall do so at his/her
            own risk and expense and apprise himself/herself of their terms and
            conditions and privacy practices.
          </p>
          <p>
            <b>9. Grievances and Contact Details</b>
          </p>
          <p>
            In the event of any queries or grievances You may contact{" "}
            <b>Ritesh Kumar</b> at ritesh@legistify.com.
          </p>
          <p>
            <b>10. Jurisdiction</b>
          </p>
          <p>
            This Privacy Policy and its provisions shall be construed in
            accordance with and governed by laws of India and any disputes
            hereunder shall be subject to the jurisdiction of the courts
            situated at Delhi.
          </p>
        </CardBody>
      </Card>
    </Fragment>
  );
};

export default Policy;
